name: finance_calculator
description: "A suite of financial calculators."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  csv: ^5.1.1
  finance_updated: ^0.1.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.20.2
  ml_dataframe: ^1.6.0
  ml_linalg: ^13.12.6
  provider: ^6.1.2
  shared_preferences: ^2.3.0
  undo: ^1.5.0
  flutter_web_plugins:
    sdk: flutter
  string_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
